springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

knife4j:
  enable: true
  setting:
    language: zh_cn

# Mongo数据库连接配置
spring:
  datasource:
    url: jdbc:postgresql://10.2.3.36:5432/movie_api
    username: api
    password: api